### ISSUE TITLE
Estilo visual

### ISSUE THREAD

**Issue by vcalzadaga** [CIFP-Jose-luis-Garci/Shakun#1]
Concept art
Diseño de personajes
Diseño de escenarios
Objetos, power ups, coleccionables...
Mapas, botones...

**Comment by vcalzadaga** [comment]
Este es el modelo del concept

**Comment by LauFranky** [comment]
**Diseño de personajes (Shönu)**
![Niño_prota](https://user-images.githubusercontent.com/90465415/140992855-f2f6bd21-1b9b-4e4e-914b-53633d948b06.jpg)
![Niño_turnaround](https://user-images.githubusercontent.com/90465415/140993021-4ef81724-56c5-4342-92eb-81d699175bf4.jpg)
![Niño_prota_(Paleta_de_color)](https://user-images.githubusercontent.com/90465415/140993067-b54ec3b8-ea5b-43e6-98df-5e6bd4d4b710.jpg)
![Niño_prota_(Paleta_color_azul)](https://user-images.githubusercontent.com/90465415/140993185-99926ef6-ac16-4057-b494-81d0dc63d323.jpg)

**Comment by LauFranky** [comment]
**Diseño de personajes (Geylong)**
![image](https://user-images.githubusercontent.com/90465415/141165681-e3dc9760-2e3a-430d-9d3b-ea88f414382c.png)
![image](https://user-images.githubusercontent.com/90465415/141165839-b7027326-81e3-48d2-ad70-77b27ed81e4b.png)
![image](https://user-images.githubusercontent.com/90465415/141165945-95ccc696-aa3e-4b0d-893d-16b323698460.png)

**Comment by LauFranky** [comment]
**Diseño de personajes (Ejemplo enemigo humano)**
![image](https://user-images.githubusercontent.com/90465415/141166149-df15573a-de6f-47aa-be01-e72751b5bae2.png)

**Comment by LauFranky** [comment]
**Diseño de personajes (Ejemplo enemigos criaturas)**
![image](https://user-images.githubusercontent.com/90465415/141166498-e2ee83dc-ad89-446e-b111-02b9156e5ae0.png)

**Comment by LauFranky** [comment]
**Diseño de personajes (Ejemplos dragones)**
![image](https://user-images.githubusercontent.com/90465415/141166644-899f5d7b-a045-4e76-be1e-14600a392a04.png)
![image](https://user-images.githubusercontent.com/90465415/141166690-c43f61f0-41e4-4cde-bff7-3a6dfa9f5f58.png)

**Comment by LauFranky** [comment]
**Diseño de escenarios (Nivel de Introducción)**
![image](https://user-images.githubusercontent.com/90465415/141167929-367119d9-75dd-46f6-bc2d-8fc5270643b9.png)
![image](https://user-images.githubusercontent.com/90465415/141167974-be64a9ba-ec1a-4027-880b-61410fccb19f.png)

**Comment by LauFranky** [comment]
**Diseño de escenarios (Mapa)**
![image](https://user-images.githubusercontent.com/90465415/141168148-b7b33ae3-023f-4563-ad3e-969cef6cf160.png)

**Comment by LauFranky** [comment]
**Diseño de escenarios (Nivel 1: Tierra)**
![image](https://user-images.githubusercontent.com/90465415/141168281-f2d7dc72-107c-4035-bdd7-b7726044b63d.png)
![image](https://user-images.githubusercontent.com/90465415/141168424-eb93a6b7-5226-46a8-a621-e40bb2082c6a.png)

**Comment by LauFranky** [comment]
**Diseño de escenarios (Nivel 2: Agua)**
![image](https://user-images.githubusercontent.com/90465415/141168693-069d2830-212e-4168-84c7-ec00c00d602b.png)
![image](https://user-images.githubusercontent.com/90465415/141168739-550bc31f-14c1-40a8-b80d-4ad736e9fa0f.png)
![image](https://user-images.githubusercontent.com/90465415/141168783-2296df5a-333f-4bbf-a183-f049ca5ade86.png)

**Comment by LauFranky** [comment]
**Diseño de escenarios (Nivel 3: Aire)**
![image](https://user-images.githubusercontent.com/90465415/141168953-00815099-ab07-4e5a-b32b-4fe360533bec.png)
![image](https://user-images.githubusercontent.com/90465415/141168984-dd6d7f3d-35a9-4c61-b40f-6095ff8c78f1.png)

**Comment by LauFranky** [comment]
**Diseño de escenarios (Nivel 4: Luz y Oscuridad)**
![image](https://user-images.githubusercontent.com/90465415/141169286-1e553390-e46d-4d5f-a16d-8557f7f0127c.png)

**Comment by LauFranky** [comment]
**CONCEPT ART**
**Diseño de personajes**


- **Shonu**
Diseño principal:

![image](https://user-images.githubusercontent.com/90465415/141358900-2c436f12-5826-40f1-a8d0-42425d8d76a0.png)

Turn around:

![image](https://user-images.githubusercontent.com/90465415/141359121-d65c2981-84bc-4538-a457-347d52e4470c.png)

Pruebas de color:

![image](https://user-images.githubusercontent.com/90465415/141359257-edd7f44a-318d-4952-bfef-8186a930904f.png)
![image](https://user-images.githubusercontent.com/90465415/141359292-85af2eb0-2ca4-4590-9478-1a640478e523.png)


- **Geylhon**
Diseño principal:

![image](https://user-images.githubusercontent.com/90465415/141359486-00865193-7d34-4566-abe5-5fc356489511.png)

Turn around:

![image](https://user-images.githubusercontent.com/90465415/141359621-57e6af9a-32c2-4e1e-a316-14f3ce293c46.png)

Pruebas de color:

![image](https://user-images.githubusercontent.com/90465415/141359677-b70f5c9f-8dff-478b-9f99-6bc9b9d7f2a3.png)


- **Ejemplo enemigo humano**

![image](https://user-images.githubusercontent.com/90465415/141359843-b9cfcae3-9720-45d9-ba61-7eb17eef864d.png)


- **Ejemplo enemigos criaturas**

![image](https://user-images.githubusercontent.com/90465415/141359904-5dfcbbfd-5207-44f2-a3ed-f83e0c84b417.png)


- **Dragones**

![image](https://user-images.githubusercontent.com/90465415/141359983-b6e06524-746a-41df-bf7a-05bd48477e19.png)
![image](https://user-images.githubusercontent.com/90465415/141360055-2915c682-c95b-4062-9ffe-a0b5e36b6fe5.png)


**Diseño de escenarios**

**Introducción del juego:**

![image](https://user-images.githubusercontent.com/90465415/141360300-680bac06-4472-4c71-bd5b-06fcc965f7ad.png)
![image](https://user-images.githubusercontent.com/90465415/141360327-cb33ebb1-4a89-4ba2-b8c8-4ac8657e593f.png)

**Nivel 1. Tierra:**

![image](https://user-images.githubusercontent.com/90465415/141360422-fbe820fa-ffd4-496a-9ce3-3c47bac26dd4.png)
![image](https://user-images.githubusercontent.com/90465415/141360435-ec6bd8f8-c890-4288-8994-30e997024667.png)

**Nivel 2. Agua:**

![image](https://user-images.githubusercontent.com/90465415/141360524-276a12dd-8f60-4e32-80b3-eae445548f7f.png)
![image](https://user-images.githubusercontent.com/90465415/141360542-be8eabef-47e3-4913-b4f7-28e43308e0c5.png)

**Nivel 3. Aire:**

![image](https://user-images.githubusercontent.com/90465415/141360663-dd18e52e-d893-4e0d-a5a1-c40b34f4541b.png)
![image](https://user-images.githubusercontent.com/90465415/141360676-200e7828-eacb-4386-a0d9-7bab1113d07b.png)

**Nivel 4 y 5. Luz y Oscuridad/ Espacio-Tiempo:**
![image](https://user-images.githubusercontent.com/90465415/141360764-3f8dcb35-151a-4050-81dd-c7b9ee43dace.png)


En el videojuego no se usarán objetos u otros coleccionables durante la aventura, sin embargo, la forma en la que el protagonista recarga su energía para poder luchar con los poderes de dragón es a través de unos altares de dragón que estarán esparcidos por el mapa. Estos altares tendrán este aspecto:

![Altar](https://user-images.githubusercontent.com/90465415/141364943-cb95b7f3-ccd0-4b3e-a2fd-52b11cf4112e.jpg)


**Mapa**

![image](https://user-images.githubusercontent.com/90465415/141365080-2c509644-0653-40cb-baa5-6df44cd17100.png)


**Botones**
Los botones de inicio y de selección tendrán este aspecto:

![image](https://user-images.githubusercontent.com/90465415/141365197-539ad55a-289b-47b3-b4e1-d10df8d71daa.png)


El HUD tendrá esta organización:

![image](https://user-images.githubusercontent.com/90465415/141365468-acc03136-45da-4ca2-9c67-5c4f59124897.png)
