### ISSUE TITLE
Dinámicas y mecánicas

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#10]

**Comment by vcalzadaga** [comment]
Un título que os puede dar ideas con respecto a la mecánica de carga de energía es Infamous. Os paso un gameplay del juego por si os sirve de inspiración
https://www.youtube.com/watch?v=SEH9L4nqO28

**Comment by monocleduck** [comment]
MECÁNICAS
EL desarrollo del juego se centra principalmente en el movimiento y la lucha de nuestro protagonista; cada vez que avanze en a historia, se irá haciendo cada vez más fuerte, ampliando su arsenal y herramientas para poder seguir con su aventura.

El movimiento del juego se basará en simples mecánicas como serían:
- Un salto, usado para ganar altitud.
- Andar y correr para desplazarse por el mapa.
- Habilidades de mobilidad, como podría ser un dash, para desplazarse rápidamente.

La lucha se basará en el uso de varios ataques diferentes, combinados con el movimiento para sacar el máximo provecho del gameplay:
Por eso mismo, nuestro portagonista poseerá una grán variedad de ataques a su disposición que se comportarán de manera diferente.
De primeras tendremos cuatro ataques diferentes:

Normal
Pasiva: mientras se usen ataques de ésta estancia, la energía se generará más rápidamente.
L2- Sucesión de golpes rápidos que dañará en area y aturdirá a los enemigos
R2- Patada con salto hacia atrás que te distancia de los enemigos, los daña, y los empujará lejos del jugador.
L1- Ataque deslizante que barre a los enemigos, los manda por los aires, y los daña.
R1- Palmada hacia delante que inflije gran daño y aturde a los enemigos.

Al conseguir cáda nuevo poder elemental, el jugador podrá equiparse dicho elemento con una rueda de acción en cualquier momento jugable (eso excluye menús, pantallas de carga, cinemáticas…), al hacer esto, sus ataques, modo de moverse, y pasiva cambiarán por unas que estén ambientandas en el nuevo elemento.

Tierra 
Pasiva: sus movimientos son más lentos en general, pero hacen más daño 
L2- Crea un parche de terreno que impulsa a enemigos y aliados, aturdiéndolos (a los enemigos) y dejando terreno que impide el paso 
R2-Dispara una roca gigante contra sus enemigos 
L1-Pega un puñetazo al suelo que provoca un terremoto derribando a sus enemigos y crea pinchos que surgen desde el suelo y hacen daño a sus enemigos 
R1-Crea un escudo 
Cuadrado- Crea una espada 
Triángulo-Crea un martillo 

Agua 
Pasiva: Sus golpes hacen Knock Back
 L2- Curar
 R2- Dispara burbujas anti gravitatorias que atrapan a sus enemigos
 L1- Chorro a presión que puede dirigir Circulo-Se convierte en una ameba de agua que se vuelve invencible durante unos segundos
 
Viento 
Pasiva- Sus movimientos y sus golpes son más rápidos
 L1- Tornado que vaya en una dirección 
R2-Dispara una ráfaga de aire que echa a sus enemigos hacia atrás
 L2-Rafaga de 30 golpes súper rápidas 
Circulo- El personaje se impulsa en el aire y hace retroceder a sus enemigos
 X- Se impulsa en el aire y si lo mantiene planea

 Luz/Oscuridad 


R2-Tira una bomba de luz que explota
R1- Ataque de luz que ciega a sus enemigos
L2- Ataque de oscuridad muy lento pero que haga mucho daño 
L1 - Invoca a un dragón de luz y otro de oscuridad que hace daño en un área de circulo

Éstos ataques podrán fluir entre unos y otros gracias a la función de ralentizar el tiempo que se aplicará cade vez que abramos la rueda de poderes, de ésta manera, podremos combinar varios ataques de diferentes elementos en sucesión sin parar el ritmo.

En caso de que el gameplay se vea afectado por el abuso de cambio de poder, se aplicarán cambios en los enfriamientos y demás números para alentar un correcto flow.


Además de éstos ataques, el personaje contará con una barra de vida que se irá reduciendo cada vez que el personaje sea golpeado, cuando la barra llegue a 0, el personaje muere.
Por otro lado, existirá otra barra de “energía” la cual irá agotándose a medida de que se usen los poderes, y rellenandose cuando acabe con los enemigos, en el caso de que la barra llegase a 0, el jugador se vería obligado a usar su kit de ataque y movimiento básico hasta que se obtenga energía de nuevo. Adicionalmente, habrá objetos interactuables por el mapa capaces de otorgar energía.

Además de todo esto, el jugador podrá interactuar con personas y objetos del entorno al pulsar el botón de interactuar cerca de los mismos.
El juego será de mundo abierto, pero la progresíon del juego estará drásticamente basada en el progreso de los Niveles en los que se desarrolla cada ciudad, por lo que será de vital importancia, ser además capaz de poder abrir un mapa para saber dónde se encontrará nuestro próximo objetivo o simplemente, para localizar puntos de interés. En dichos niveles, también encontraremos elementos como puzles en los que habrá que resolver aplicando lógica y a veces  los poderes y movimientos del personaje para resolverlos.

DINÁMICAS

La dinámica fundamental serán varias:
La principal será la de Recompensa; ya que, el jugador al golpear y luchar contra los enemigos, obetendrá una sensacíon satisfactoria a la hora de golpear a los enemigos y obtener nuevos poderes al avanzar en la historia.
Seguida de ésta, tendremos la dinámica del interes, ya que el mundo estará repleto de lugares que explorar y visitar.

**Comment by monocleduck** [comment]
![81B1h7W5NLL _AC_SL1500_](https://user-images.githubusercontent.com/79661590/141171158-defb1352-a813-4ba4-94f7-4f9aa7816d58.jpg)

Ejemplo visual de controles de mando
