### ISSUE TITLE
Movimientos y físicas

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#11]
-Controles: durante el juego (si el jugador puede utilizar gamepad y teclado, indicar los
controles de ambos dispositivos) y en la navegación por lo menús.
-Interacción entre elementos.

**Comment by monocleduck** [comment]
MOVIMIENTOS Y FÍSICAS

CONTROLES:
EL jugador podrá jugar tanto en mando como en teclado y ratón, aunque es aconsejable jugar en mando.
MANDO:
Los gatillos, (R2, R1, L2, L1) estarán dirigidos mayoritariamente a castear los ataques, con posibilidad de aumentar a los botones como cuadrado circulo y demás.
Los joysticks se usarán para el movimiento tanto de la cámara como del personaje (una para cada uno)
El botón X se usará para saltar, y el círculo para dashea…. dependiendo en parte de la estancia de poder en la que se esté.
Triángulo para interactuar con el entorno.
La cruzeta servirá para cambiar de poder, cáda dirección será un poder diferente, y en el caso de que se use la direccion de un poder que se está usando, se cambiará al modo sin poder.
El botón de start se usará para abrir el menú de opciones.
El botón back abrirá el mapa, en el cual

En el menú de opciones se podrán usar tanto los joysticks como la cruzeta para navegar por el menú, y el botón cuadrado y círculo para aceptar y rechazar opciones, los joysticks se usarán además para cambiar valores  de las opciones una vez tengamos ésta seleccionada.





TECLADO Y RATÓN:
El manejo del teclado se basaría en botones q y e para elegir patada o puño, y  los botones del ratón se usarán para elegir ataque 1 o 2 de patada/ puño.
Las teclas W A S D estarán destinadas al movimiento del personaje, y el movimiento del ratón para el de la cámara.
Barra espaciadora para saltar, CTRL para correr, y SHIFT para dashear, dependiendo de la estancia de poder.
R se usará para interactuar con el entorno.
El botón Escape para abrir el menú de opciones, en el que se podrán usar tanto las flechas como wasd comoratón para navegar por el menú, y los botones del ratón o Q y E para aceptar o rechazar; los sliders serán afectados por el ratón las flechas izquierda y derecha y A y D.
M para  abrir el mapa de mundo
Y para abrir la rueda de poderes pulsaremos la tecla F, la cual abrirá el menú, y dentro de éste usaremos el movimiento del ratón para navegar por los diferentes poderes, para seleccionar un poder usaremos el botón izquierdo del ratón y para cerrar el menú usaremos el derecho.


FÍSICAS

El juego se desarrolla en un entorno tridimesional, por lo que el personaje estará limitado a desplazarse por las zonas a la sque sea posible llegar mediante el movimiento, ya que diferencias de altura y colisiones con paredes limitarán el acceso a ciertas áreas.
Al usar sus ataques, el personaje entrará una fase de animación para realizarlo, los enemigos tendrán que estar en el rango de efecto de ataque para ser afectados, lo mismo ocurrirá con los ataques de los enemigos sobre el jugador, las entidades afectadas sufrirán las consecuentes penalizaciones como podrían ser pérdida de vida, efectos negativos, aturdición, etc.

Dependiedo de la estancia de poder, el jugador será capaz de desafiar algunas leyes, como podría ser la habilidad de planear con la estancia de viento.

**Comment by monocleduck** [comment]
![mando bien hecho](https://user-images.githubusercontent.com/79661590/141179171-4445ed54-3b63-4f65-bd2e-1b4f8c9ef046.png)
