### ISSUE TITLE
Diseño de niveles

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#13]
-Objetivo del jugador.
-Flujo de juego: explicar el transcurso de una partida, los pasos a seguir desde que el juego arranca hasta completar un nivel completo.
-Niveles del juego: describir sus características principales, los enemigos u obstáculos que encontrará el jugador, con especial incidencia en el nivel que tenemos pensado desarrollar para la práctica final.
- Dificultad: hablar de la progresión de la dificultad durante el juego. Elaborar un diagrama.
- Tutorial: cómo lo vamos a integrar. Vamos a utilizar texto o no. Influencias de otros títulos en los que nos hemos inspirado.

**Comment by monocleduck** [comment]
DISEÑO DE NIVELES

OJETIVO DEL JUGADOR:

El objetivo del jugador es el de llegar al final de cada nivel para gradualmente librear los dragones y obtener sus poderes. El último nivel tendrá como objetivo detener al villano.

FLUJO DE JUEGO:
El jugador será transportado al mundo abierto por el cual podrá desplazarse y explorar, al llegar a la destinación de un nivel, el jugador será transportado a un mapa más cerrado por el que tendrá que atravesar venciendo enemigos y resolviendo problemaas de puzle y plataformeo. Al llegar al final de un nivel, el jugadro se enfrentará a una especie de mini boss temático de el nivel, al que derrotará para así poder terminar el nivel. Repartidos por el nivel habrán puntos de control que se usarán para poder cargar partida una vez se salga del juego o se muera.

NIVELES DEL JUEGO
NIVEL 1: 
Shöun se infiltra en una de las bases en las que se guardan uno de los dragones, se va a mover sigilosamente hasta llegar al dragón de tierra, intenta escabullirse de los enemigos y liberar al dragón. Se desarrollará en un pueblo será árido con la base del pueblo en una cueva. 
Al encontrarnos en una cueva y ser relativamente débiles, tendremos que hacer uso de las mecánicas de nivel que consistirán en escabullirse de los enemigos al ocultarse dentro de objetos como podrían ser cajas o un montón de paja… El nivel durara aproximadamente unos 30 minutos. 

NIVEL 2: 
El siguiente pueblo, se encuentra en el pueblo portuario en la costa del país. Shöun al llegar al pueblo usa los poderes adquiridos del dragón de tierra para poder liberar al dragón de agua que esta capturado por los habitantes de este pueblo. 
Debido a que nos encontramos en un poblado directamente encima de unas aguas termales, las mecánicas de nivel estarán altamente relacionadas con el agua y el vapor. Por ejemplo, habrá momentos en los que en sitios específicos, un gran geiser de agua caliente romperá el suelo de madera, el cual dañará a todo el que entre en contacto, haciendo que éstos sean un gran peligro para nosotros, a la vez que un buen aliado a la hora de acabar con nuestros enemigos, ya que podremos empujarlos hacia el geiser; además, nos encontraremos con puntos en los que se formarán fuertes corrientes de agua, las cuales arrastrarán a todo lo que se acerque, haciendo que Shöun tenga que encontrar un lugar con el que protegerse.
 El nivel durara aproximadamente unos 30 minutos. 

NIVEL 3: 
Shöun se embarca en el pueblo del aire, que consiste en una población que se mantiene a flote en los cielos gracias a su líder, utilizan los poderes del aire para impulsar el zepelín en el que se embarcan. En este pueblo tendrán capturado al dragón del aire y el niño es el encargado de salvarlo.
 En éste nivel, ya que todo ocurre en una gran ciudad volante, habrá varias mecánicas centradas en el aire y las alturas. Habrá varias zonas que por unas cosas o por otras, se deban sortear realizando saltos para evitar caer al vacío, además, habrá varios lugares en donde haya grandes ventiladores que generen fuertes ráfagas de viento que impulsarán todo lo que se acerque, dando así la oportunidad de hacer niveles con mayor verticalidad, y dando una mayor velocidad a la acción. 
El nivel durara aproximadamente unos 30 minutos. 

NIVEL 4: 
Tras salir del pueblo del aire, Shöun usa el zepelín para llegar a la ciudad. En la ciudad se encuentran el dragón de luz y oscuridad, que lo mantienen encerrado. El niño tendrá que luchar contra pueblo para poder salvarlo. 
Tratándose de la ciudad en la que se encuentra el dragón de luz y oscuridad, todas las mecánicas girarán en torno a dicha temática. La ciudad estará repleta de lámparas que irán encendiendo y apagándose para dificultar el avance de Shöun, creando absoluta oscuridad en ciertos momentos, para así sorprender al jugador con varios enemigos que momentos antes no estaban en pantalla; éstas mismas lámparas serán interactuables, dando la posibilidad de crear puzles que juegan con las sombras para encontrar la solución. 
El nivel durara aproximadamente unos 45 minutos.

 NIVEL 5: 
La trama se desarrolla en misma ciudad, el líder de los humanos, Geylhon, se encuentra en la ciudad, pero posee los poderes del dragón del espacio-tiempo, lo va cambiando según su antojo. 
Debido a que el hombre con los poderes del dragón del espacio-tiempo, Geylhon, sabe que Shöun está en la ciudad y ha vencido al dragón de luz y oscuridad, está enfurecido, por lo que va cambiando mediante sus poderes la ciudad entere en un intento de acabar con el joven. Todas las mecánicas de los anteriores niveles se aplican a éste, junto con unas nuevas mecánicas que introducen burbujas temporales (espacios en los que el tiempo transcurre de manera diferente). 
En este nivel se produce la lucha final entre Shöun y Geylhon, Shöun consigue derrotar a Geylhon y salvar al último dragón, el dragón del espacio-tiempo. Cuando derrota al líder se acaba el juego. El juego termina con la victoria de Shöun y todos los dragones liberados. Los dragones como gratitud de haber sido salvados le conceden al niño todos sus poderes para que siga protegiéndoles.
 El nivel durara aproximadamente unos 45 minutos.


CURVA DE DIFICULTAD

 

La dificultad será gradualmente más dura a medida que avanze el juego, el nivel de poder del personaje estará levemente por debajo de ésta para hacer la experiencia algo desafiante, aún así, el nivel de los enemigos será menor que el de el personaje para darle ese toque hack & slash de sentirse poderoso al acbar con varios enemigos. Evidentemente, los bosses tendrán un nivel de poder igual o mayor al del jugador, para mostrar otro desafío.
La dificultad cambiará en función del modo que se haya escogido.

TUTORIAL
El tutorial consistirá en un primer nivel en el que se enseñará lo báscio por medio de texto en pantalla y algunas misiones. A medida que se desbloqueen poderes, el personaje podría volver a su templo para practicar con ellos, o simplemente experimentar para ver cómo funcionan, ya que los efectos son muy intuitivos y directos.

**Comment by monocleduck** [comment]
Tengo la gráfica de dificultad pero no se como subirla.

**Comment by monocleduck** [comment]
Ahora si se :DDDDDD

![Diseño sin título](https://user-images.githubusercontent.com/79661590/141170605-7c6c4664-af8e-4993-badd-4106877854f0.png)
