### ISSUE TITLE
Música y efectos

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#14]
Hablar del estilo sonoro que tendrá el juego y recopilar algunas músicas y efectos representativos.

**Comment by MaikDitz** [comment]
Para nuestra música ambiental que va a estar de fondo en nuestro juego hemos pensado en usar estas dos bandas sonoras como referencia:
-https://youtu.be/P2JNQhAsIHA
-https://www.youtube.com/watch?v=0NhwEQEercE
Luego, cuando entremos en combate necesitamos unas canciones más fuertes y energéticas, para ello hemos pensado en la banda sonora de Monster Hunter World, cuando el personaje entra en un combate.
https://www.youtube.com/watch?v=orBbvNw5N0U
