### ISSUE TITLE
Referencias

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#15]
Otras obras (videojuegos, libros, películas… ) que nos han influido para diseñar el juego. Por cada título que mencionemos, tenemos que indicar en qué aspectos concretos nos hemos inspirado.

**Comment by MaikDitz** [comment]
Empezamos explicando las referencias audiovisuales que hemos usado para tener unas bases de nuestro juego. Primero, para la cámara queremos que sea un juego en 3ª persona con un ángulo picado centrado enseñando la espalda de nuestro personaje, para tener mejor control visual de lo que esta pasando, basandonos en NieRAutomata.
![imagen_2021-11-10_060037](https://user-images.githubusercontent.com/90465468/141052801-45b42e56-808d-4091-bc99-14df65db67ed.png)

Para el sistema de energía tenemos el juego de ori, que a base de coger orbes o objetos que nos puedan devolver maná y vida, aunque también podremos obtener maná si nos quedamos sin nada, es decir, que se recarga con el tiempo poco a poco.
![descarga](https://user-images.githubusercontent.com/90465468/141052820-ad96c164-2856-4aad-a673-dcc2518564e3.png)

En base al movimiento de nuestro personaje en los combates, hemos decidido usar un sistema dinámico y con mucho movimiento como en el videojuego de Marvel's Spiderman.
![marvels-spider-man-screen-16-ps4-us-30mar18](https://user-images.githubusercontent.com/90465468/141052945-52b8ecde-ba5a-45a9-ba78-337f57249a90.png)

Por ultimo, hemos usado como referencia para el sistema de poderes el inFamous, en los que dentro de el juego, incluido en combate podremos cambiar de poderes y habilidades con un sistema de rueda de poderes desplegable.
Antes de crear a nuestros personajes necesitábamos una base para nuestro "guerrero", hasta que decidimos que fuera como un monje Shaoling pero en niño, y al villano como un guerrero chino antiguo.
![descarga](https://user-images.githubusercontent.com/90465468/141053045-cc4e4a94-4e81-4356-843b-c523899e20ac.jpeg)
![8-Kid-The-Last-Guardian-Xtreme-Retro](https://user-images.githubusercontent.com/90465468/141178224-6e0a60e2-4d38-4c3d-aa44-add2196a8465.png)


En la iluminación nos basamos en los colores vivos de el juego "Ori".
![1582731583_213451_1582731655_noticia_normal](https://user-images.githubusercontent.com/90465468/141053100-9bbe7c4d-1caa-496a-95ae-821162279be5.jpg)

Para los escenarios hemos pensado buscado varias imágenes variadas dependiendo del nivel, como por ejemplo para el nivel uno, hemos usado la aldea de arena de Naruto
![image](https://user-images.githubusercontent.com/90465468/141177354-7d44206a-3dde-4644-9383-e5d86abd5944.png)

Nivel 2: (zona de agua)
![image (1)](https://user-images.githubusercontent.com/90465468/141177552-95f29735-9a47-4159-8d5a-608768c0a6b4.png)

Nivel 3: (zona aerea)
![image (2)](https://user-images.githubusercontent.com/90465468/141177748-0b36c7fc-f359-459d-a082-c5c328c486db.png)

Nivel 4: (representando cuevas oscuras o trayectos poco iluminados)
![image (3)](https://user-images.githubusercontent.com/90465468/141177909-97eaea6f-df0a-4968-8d1d-51dfb2bcc4a4.png)

Referencias para los dragones:
Dragon de Agua:
![184563ff91109da0f1ba403881482fd3](https://user-images.githubusercontent.com/90465468/141178805-8ae279cc-3b94-41c7-8795-898661182a04.jpg)
Dragon de Viento:
![Amphithere](https://user-images.githubusercontent.com/90465468/141179173-3eeafec9-4818-4b0a-a5d2-3e093129ba33.jpg)
Dragon de Luz y Oscuridad:
![d57bb071980a896023c4a63239e580b8](https://user-images.githubusercontent.com/90465468/141179238-9c5480ea-72a3-43b7-a8f2-70fe1af95446.jpg)

**Comment by yaigh** [comment]
**REFERENCIAS PARA PORTADA DEL JUEGO**

![26fa29cf804adc1f0ad096a7a99abd87](https://user-images.githubusercontent.com/90465328/141177773-3877fc7f-d1ae-4b7d-b081-28b34f374a5c.jpg)

![ce4dee8232ac79d220aeeb1680252487](https://user-images.githubusercontent.com/90465328/141177781-3cff1d27-06dc-41df-9868-3484d40aa0a7.jpg)
