### ISSUE TITLE
Alcance

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#16]
(Según nuestra previsión inicial, tenemos que indicar hasta dónde tenemos pensado desarrollar de aquí al mes de marzo, si vamos a modelar los personajes desde cero, en qué aspectos vamos a utilizar material de librerías…)

**Comment by yaigh** [comment]
Nuestro objetivo principal es desarrollar todo juego por nosotros mismos, todos los modelados (personajes y escenarios), los texturizados, las animaciones, etc.
Pero mientras vayamos avanzando el juego veremos si vamos bien de tiempo para poder realizar todas las partes, sino, recurriremos a modelados básicos como los props, algún objeto de los escenarios o algún modelado secundario. 
En la parte de programación, dado que queremos que nuestro juego fluya lo mejor posible pues puede que si recurramos algunos recursos ya creados pero en la medida de lo posible queremos hacer todo nosotros mismos.
Lo más probable es que sí nos de tiempo ha lograr todos nuestros objetivos del juego para marzo.

**Comment by yaigh** [comment]
Nuestro objetivo principal es desarrollar todo juego por nosotros mismos, todos los modelados (personajes y escenarios), los texturizados, las animaciones, etc. 
Pero mientras vayamos avanzando el juego veremos si vamos bien de tiempo para poder realizar todas las partes, sino, recurriremos a modelados básicos como los props, algún objeto de los escenarios o algún modelado secundario.
En la parte de programación, dado que queremos que nuestro juego fluya lo mejor posible pues puede que si recurramos algunos recursos ya creados pero en la medida de lo posible queremos hacer todo nosotros mismos.
En conclusión, ya tenemos planteado quien se va a encargar de cada parte del trabajo, la organización del tiempo y de tareas, asique lo más probable, es que sí nos de tiempo ha lograr todos nuestros objetivos del juego para marzo.

**Comment by vcalzadaga** [comment]
Creo que la previsión es demasiado optimista. Deberíais afinar un poco más o, al menos, determinar un orden de prioridad en cada tarea. Por ejemplo: modelaremos el personaje principal, el primer nivel y el primer NPC. Si nos da tiempo, modelaremos también esto o aquello

Intentad que sea lo más realista posible

**Comment by yaigh** [comment]
Nuestro objetivo principal es desarrollar todo juego por nosotros mismos. Pretendemos hacer cada parte del proyecto que se compone en: modelar, texturizar, animar a los personajes y programar el videojuego.
En primer lugar, modelaríamos a Shonü (el personaje principal que controlara el jugador) y al primer NPC, que será un enemigo básico y no a Geylhon (el Boss al final del juego) porque así al empezar a crear el videojuego, empezaríamos por los primeros niveles y tendríamos más tiempo para crear al enemigo principal en el transcurso del videojuego. En segundo lugar sería crear los primeros terrenos para los niveles y los props necesarios pero muy básicos. Como tenemos el propósito de hacer una Demo antes de hacer el juego completo, hemos pensado en desarrollar primero un nivel, el nivel del aire, que consistiría en una especie de zepelines como escenario principal. 
Por lo tanto, pensamos que nos daría tiempo a modelar todo lo que tenemos pensado, que es: un zepelín (modelaríamos uno solo para después usar varios de ellos pero partiendo del mismo modelado) para el escenario de ese nivel, a Shoü y el primer NPC.
En tercer lugar, sería texturizar todo, pero al usar el programa de Unity utilizaríamos texturas muy simples porque el programa no soporta grandes texturas, ya que no tiene un motor gráfico lo suficientemente potente para mover tantos objetos con muchas texturas y eso haría que ralentizarían las animaciones del videojuego, por eso, vamos a utilizar un texturizado muy sencillo.
Por último, lo que vemos más complicado, sería crear todas las animaciones principales de Shonü y del NPC, además, de programar todo el videojuego y las animaciones para que todo fluya bien. Puede que eso es lo que nos lleve más tiempo y nos suponga mayor trabajo pero igualmente intentaremos secarlo adelante, sino, buscaremos soluciones sencillas, como, coger scripts de movimientos ya creados.
En conclusión, ya tenemos todo planteado, quien se va a encargar de cada parte del trabajo, la organización del tiempo y de tareas, asique, lo más probable es que sí nos de tiempo ha lograr nuestro objetivo principal del juego que es hacer la Demo.
Pero mientras vayamos avanzando el juego veremos si vamos bien de tiempo a todo lo que tenemos programado hacer, o si nos va ir funcionando bien cada parte, sino, tiraremos de recursos, como, los rigg para los personajes, scripts de otros usuarios o otros juegos para la parte de programación, y más recursos que iremos necesitando.
