### ISSUE TITLE
Público objetivo (target)

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#17]
Cuanto más específico sea, mejor. Relacionar con los datos publicados en el anuario AEVI.

**Comment by yaigh** [comment]
El principal objetivo de Shak'un es proporcionar a nuestros jugadores la mejor experiencia posible en nuestro juego, un videojuego de plataforma en 3D que esta dedicado a un mundo de fantasía. Por eso, nuestro público objetivo son personas entre 12 -30 años, gente con experiencia en videojuegos que ya hayan jugado a juegos de Hack & Slash y  les guste ese tipo de género. Además, nos dirigimos a personas que les guste los mundos de ficción, la fantasía, como los dragones y criaturas sobrenaturales, y el concepto de salvar a la naturaleza.

**Comment by vcalzadaga** [comment]
Issue cerrado, no hay más modificaciones

**Comment by vcalzadaga** [comment]
Has que trabajarlo más... (ejemplo)

**Comment by yaigh** [comment]
El principal objetivo de Shak'un es proporcionar a nuestros jugadores la mejor experiencia posible en nuestro juego, un videojuego de plataforma en 3D que esta dedicado a un mundo de fantasía. Por eso, nuestro público objetivo son personas entre 12 - 30 años, gente con experiencia en videojuegos que ya hayan jugado a juegos de Hack & Slash y les guste ese tipo de género. Además, nos dirigimos a personas que les guste los mundos de ficción, la fantasía, como los dragones y criaturas sobrenaturales, y el concepto de salvar a la naturaleza.
Debido al rango de edad tan amplio al nos queremos dirigir podemos sacar beneficio de ello porque jugarían desde los más jóvenes, donde compartirían su experiencia a través de las redes sociales, con familiares y amigos, y nos darían cierta publicidad, hasta los adultos, donde podrían experimentar con el juego y son los que podrían generar más beneficios en nuestro proyecto porque es un perfil que se caracteriza porque la mayoría tienen trabajan y tienen ingresos.
