### ISSUE TITLE
Equipo humano

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#18]
- Relación de los miembros del equipo con los perfiles profesionales: ¿De qué nos vamos a encargar cada uno?
- Background del equipo: breve recorrido por la historia del equipo y sus componentes. Incluir alguna fotografía dentro del entorno de trabajo.

**Comment by yaigh** [comment]
Shak'un no es solo un videojuego, es un gran proyecto que hemos desarrollado como un gran equipo. Nosotros estamos muy contentos con todo el trabajo  que hemos dedicado a este proyecto y el gran resultado que estamos teniendo. 
Todo empezó con un trabajo de clase, con la maravillosa idea de una de las componentes del grupo, Laura, que era crear un videojuegos en el que los dragones fueran los protagonistas,  ya que en la mayoría de las historias siempre se derrota a los dragones, lo veía algo injusto, por eso quiso dar un punto de vista distinto donde los malos era la raza humana, que estaban destruyendo el mundo, y los buenos eran los dragones, son los sustentadores de elementos para que el mundo sobreviva.

Shak'un esta compuesto por:
- **LAURA GABRIELA FRANKIEWICZ MANSO**: una gran artista, se encarga de todo el desarrollo de la historia, las ideales más importantes y el guion del videojuego; el concept art, como, la creación los personajes, tanto nuestros personajes protagonistas y secundarios; del modelado principal, de Shonü y de las criaturas enemigas; y ayuda en el texturizado.
- **YAIZA GÓMEZ HERRERO**: organizadora del proyecto, es la que desarrolla toda la animación principal, incluyendo el rigg y el skinning de los personajes; también, contribuye en la programación y en una pequeña parte del texturizado.
- **MICHAEL DIEZ LOAIZA**: se dedica sobre todo al texturizado, a las mecánicas y la interfaz del juego, además, ayuda en el diseño de los niveles y la animación.
- **GUILLERMO CABEZAS ARÉVALO**: es el encargado principal de la toda la programación del videojuego y el diseño de niveles y también colabora en el desarrollo de las mecánicas.
