### ISSUE TITLE
Sistemas de partículas

### ISSUE THREAD

**Issue by alhgo** [CIFP-Jose-luis-Garci/Shakun#19]
Aunque queda mucho desarrollo todavía, creo que es importante ir investigando cómo crear sistemas de partículas impactantes, porque en un juego como este es el que le da calidad. Dejo aquí algunos vídeos que pueden ayudarnos (veremos que se pueden crear efectos impactantes a partir de imágenes 2D):

Lanzar conjuros a partir de imágenes creadas en Photoshop:
https://www.youtube.com/watch?v=-P09r-ALN38

Un slash básico: 
https://www.youtube.com/watch?v=sHZRzrsgK4k

Crear ataques usando mallas diseñadas previemente:
https://www.youtube.com/watch?v=qDu_6x4SNzY

Y más que veremos por ahí.

**Comment by yaigh** [comment]
Estoy investigando todo lo que puedo sobre el sistema de partículas y decidiendo lo que vamos hacer cuando las animaciones estén acabadas.

**Comment by alhgo** [comment]
Ahora que hemos decidido pasar a URP en Unity, y podemos usar Shader Graph y VFX, recomiendo explorar la posibilidad de usarlo para crear sistemas de partículas a partir de shaders. Aquí un vídeo que por ejemplo muestra cómo crear rayos: https://www.youtube.com/watch?v=40m_HUENh3E

**Comment by yaigh** [comment]
**TURORIALES VFX DE UNITY QUE PODEMOS UTILIZAR**:
- https://www.youtube.com/watch?v=u9lOaPVtSqg (Electricidad)
- https://www.youtube.com/watch?v=sgBbnF3r60U&t=3s (Ataques)
- https://www.youtube.com/watch?v=IVj7-usBxHo (Sangre)
- https://www.youtube.com/watch?v=1GPvI-5bOSk (Hacer brillar a las estatuas de dragones)
- https://www.youtube.com/watch?v=H5QZhChfa1I (Brillo para las armas)
- https://www.youtube.com/watch?v=ePbeaYuMNK4 (Efectos para los personajes)
- https://www.youtube.com/watch?v=w0znZIuvQ2I (Efectos para portales)
- https://www.youtube.com/watch?v=jSIan1cEYTI (Impactos)


**Más tutoriales interesantes**: (No son para el juego, solo son interesantes)
- https://www.youtube.com/watch?v=ftCyZ7F5q9E (Efecto de nieve)
- https://www.youtube.com/watch?v=glSsaRpHKos (Efecto fuego)
- https://www.youtube.com/watch?v=SNP5QqAQqn4 (Aurora Boreal)
- https://www.youtube.com/watch?v=h4SBACYb26k (Librería mágica)

**Comment by alhgo** [comment]
Buen trabajo de investigación. Os recomiendo, si no lo habéis hecho ya, crear una escena de pruebas en vuestro proyecto de Unity y la persona encargada de esto que empiece a trastear con materiales y efectos, y lo que vaya consiguiendo lo podrán usar el resto en el proyecto final. 
Para usar Shader Graph tenéis que tener actualizado el proyecto al Universal Render Pipeline (que ya debería estar), pero para usar los VFX tenéis que instalar el paquete "Visual Effect Graph". Más info en [la página de Unity](https://docs.unity3d.com/Packages/com.unity.visualeffectgraph@8.2/manual/index.html)

**Comment by yaigh** [comment]
Había instalado el paquete de Visual Effect Graph, pero me estaba volviendo loca con los tutoriales y he encontrado uno de inicio a los shaders que lo explica bastante bien para poder seguir con los demás tutoriales:
- https://www.youtube.com/watch?v=O75iGGUQXBI
- https://www.youtube.com/watch?v=Ar9eIn4z6XE
