### ISSUE TITLE
Guion de la Demo

### ISSUE THREAD

**Issue by yaigh** [CIFP-Jose-luis-Garci/Shakun#23]
- [x] En qué va a consistir la historia y el desarrollo de nivel
- [x] Pensar las animáticas
- [x] Idear las dinámicas y mecánicas para enseñar a jugar.
- [x] Instrucciones de las mecánicas que dirigirán al jugador.

**Comment by alhgo** [comment]
Tenemos algo? Si es así lo quiero ver aquí o en el repositorio. Si no tenemos nada lo que tenemos es un problema. A partir de ese guion os iré sugiriendo cuestiones importantes a resolver de cara a la programación

**Comment by LauFranky** [comment]
**Demo**: nivel del aire

**Poderes disponibles**
**TIERRA**
Puñetazo al suelo
Crea escudo de sus brazos (necesario para ciertos enemigos)
Crea espada de sus brazos (necesario para ciertos enemigos)
Levanta un trozo de terreno (esto solo en islas flotantes, no funciona en los zeppelines)

**AGUA**
Se cura (requiere bastante maná)
Burbujas anti gravitatorias (se puede usar sobre objetos o enemigos)
Chorro de agua a presión

- Inicio de la demo:
Animática hecha con dibujos simples (Laura), texto y sistema de partículas (Yaiza). Cuenta en resumen la trama y explica brevemente las victorias de Shönu en los dos niveles anteriores para poner en situación al jugador.

- Shönu llega a la ciudad del aire en un globo aerostático con una mujer. Le dice que no le puede acompañar más allá y le recomienda ver a un señor de un zeppelin para que le de ropa apropiada.

- Shönu tiene que avanzar en sigilo por la entrada y esquivar varios guardias hasta alcanzar el "portal de aire" que lo lleva a la "Isla Tienda".

- El señor de la tienda le da la ropa, pero le recomienda comprar una máscara de gas (con el deterioro del mundo por el rapto de los dragones, el aire puede ser venenoso) y unas gafas para soportar las ráfagas de viento en el exterior. No se lo puede dar gratis. Shönu tiene la idea de volver a la entrada y conseguir oro venciendo a los guardias que habían allí.
Vuelve al "portal de aire", que desde ahí le da dos opciones para viajar: de vuelta a la entrada, o hacia el zeppelin más grande, pero en ese momento solo está disponible la opción de la entrada.

- Vuelve, pelea contra los guardias, consigue el oro (solo conseguirá el oro necesario si vence a todos), vuelve a la tienda y consigue las gafas y la máscara de gas. El "portal de aire" ya le permite viajar al zeppelin más grande. 

- En este zeppelin tendrá que pelear contra aves y soportar las ráfagas de aire. Escucha a unos guardias decir que en una habitación hay un artefacto que le permitirá volar hasta la pequeña isla donde tienen al dragón. Para entrar ahí debe desactivar el sistema que mantiene activa la nave (4 llamas azules que están en distintos puntos del zeppelin).

- Shönu tiene que recorrer la nave, pelear con enemigos humanos, con una especie de perros que tienen con ellos y con aves que le ataquen (la magia las atrae).

- Apaga las 4 llamas usando el ataque de agua. Cuando apaga todas, comienza a sonar una sirena y se abren todas las puertas de la nave. Tiene que ir corriendo a habitación del artefacto volador y huirá hasta la pequeña isla donde tienen al dragón.

- Cuando llega, se ve animática. El boss habla con Shönu y primero envía a sus secuaces a por él, y cuando los deja K.O, pelean los dos.

- Cuando Shönu vence a este boss habla con el dragón, corta animática y fin de la demo.

**Comment by LauFranky** [comment]
Las animáticas serán hechas con dibujos en 2D con colores básicos y con algo de efectos con sistemas de partículas.
Dejo algo de referencia a lo que tengo pensado aquí:

![RefAnimaticas1](https://user-images.githubusercontent.com/90465415/147371568-ccf05d83-1772-4b88-9239-7506c604fcb9.JPG)

![RefAnimaticas2](https://user-images.githubusercontent.com/90465415/147371569-7e681383-a318-42ba-9943-c9a95ce14112.JPG)

Las conversaciones que hayan en el juego con los NPCs o los pensamientos que tenga Shönu no se animarán. La escena se para y oscurece y aparecen dibujos en 2D quietos en la pantalla de los personajes que estén hablando. Se vería más o menos así:

![RefConversaciones](https://user-images.githubusercontent.com/90465415/147371646-e06731b4-228b-411e-b8d1-6411e744d391.JPG)

Estas referencias las he sacado del juego "Ruined King: A League of Legends Story". Se pueden ver mejor en este video:
https://www.youtube.com/watch?v=DxUquT6qyZc&t=254s

**Comment by LauFranky** [comment]
Para organizarme mejor las animáticas, creo un nuevo issue.

**Comment by LauFranky** [comment]
**Instrucciones que recibirá el jugador sobre los controles a lo largo de la demo**

Las instrucciones sobre los controles, consejos para atacar a ciertos enemigos y demás, saldrán en momentos previos a un combate o a alguna situación en concreto (como al inicio del juego). El juego se paralizará y saldrán estos mensajes en cuadros de texto en la pantalla, con la opción de que el jugador le de a un botón después de leerlos. 
Pongo aquí un par de ejemplos. Son del Spiderman de la PS4:

![RefInstrucciones](https://user-images.githubusercontent.com/90465415/147386850-3164d45e-cf9f-463a-bcf9-fe7a2e47c1db.JPG)
![RefInstrucciones1](https://user-images.githubusercontent.com/90465415/147386856-8773496c-316d-4f76-9e6e-b4243be90e55.JPG)


- Tras la animática inicial y terminar la conversación que tiene Shönu con la mujer del globo aerostático, dará comienzo el juego. En ese momento, saldrán instrucciones para los movimientos básicos (moverse, saltar, agacharse...)
- Tras esto, Shönu tiene que atravesar la entrada en sigilo, algo que el juego completo incorporaría mucho al principio, por eso se ha pensado esto en la demo. 
- Después de volver a la entrada a pelear con los guardias para conseguir oro, saldrían las instrucciones para realizar ataques básicos de Shönu (sin los poderes).
- Cuando ya se tienen todos los objetos necesarios de la tienda y se viaja al zeppelin más grande, habrán nuevos enemigos que requieran de usar los poderes. Para estos saldrá un nuevo mesaje de instrucciones que muestre cómo se abre la rueda de poderes.

**Comment by alhgo** [comment]
El nivel que habéis planteado es muy largo y muy complejo. Me parece genial, pero seguramente tengamos que reducirlo a algo que podamos hacer. Vosotros que sabéis mejor lo que se tiene ya avanzado y lo que no decidid con qué nos quedamos y con qué no.
Las animáticas son relativamente fáciles de hacer y con una buena música y unos buenos efectos hacen subir muchos puntos al juego. Os recomiendo trabajarlas bien. Seguiré el issue al respecto.
