### ISSUE TITLE
Rigging y Skinning

### ISSUE THREAD

**Issue by yaigh** [CIFP-Jose-luis-Garci/Shakun#24]
- [ ] Rigging de Shönu
- [ ] Rigging del enemigo principal
- [ ] Rigging del enemigos secundarios 
- [ ] Rigging del dragón (opcional)

**Comment by alhgo** [comment]
Los bípedos es mejor tirar de animaciones ya hechas, porque si no el tiempo se nos echa encima:
[https://www.mixamo.com/#/?page=1&query=atack](https://www.mixamo.com/#/?page=1&query=atack)

Con el dragón lo tenemos más complicado. Buscad un asset ya hecho o quizás nos tenemos que ir olvidando de ese boss final

**Comment by yaigh** [comment]
Estoy comenzando con el rig de Shönu en maya, lo estoy haciendo con el modelado base que tenemos de él (que está en es issue de Modelado), voy hacer la estructura de huesos y los controladores. Cuando tengamos la malla arreglada y la ropa hago el skinning.

**Comment by alhgo** [comment]
Hay muchos vídeos de cómo llevar las animaciones desde Maya a Unity mediante la exportación en FBX. Os dejo [este ](https://youtu.be/sM5zE5lmr58)que es corto, pero os recomiendo hacer pruebas para comprobar que el flujo de trabajo funciona bien. A la vuelta de vacaciones haremos alguna prueba para la siguiente práctica

**Comment by LauFranky** [comment]
Antes se me ocurrió un problema que podemos tener con las animaciones, ya que no nos han eseñado a "pegar" la ropa al modelado de nuestro personaje, por lo que en una animación la ropa quedaría estática en un sitio y he encontrado un tutorial que puede venir bien.

Lo dejo por aquí porque se trata de riggear la ropa en Maya:

https://www.youtube.com/watch?v=2oZxGf_KDcw
