### ISSUE TITLE
Concept art

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#27]
- [x] Concept de Shönu (protagonista).
- [x] Concept del boss del nivel de la demo.
- [x] Concept de 3 criaturas enemigas.
- [x] Concept de 3 enemigos humanos.
- [x] Diseño visual del nivel / Concept del escenario y de los obstáculos. (Sería bueno ir eligiendo el Skydome)

**Comment by alhgo** [comment]
Si tenemos esos concpets tengo que verlos, ya sea aquí en el foro del issue o mejor aún en el repositorio. De todas formas, a estas alturas deberíamos tener el modelado y estar trabajando en las animaciones, así que ahora mismo como concept me valdría un simple boceto. 
Si no llegamos a todo, hay que eliminar enemigos y quedarnos con uno de cada raza (o menos). La decisión que se tome que quede registrada aquí.

**Comment by LauFranky** [comment]
**Concepts de Shönu**

Este es el atuendo básico de Shönu. 

![image](https://user-images.githubusercontent.com/90465415/147387320-79cecb8e-d591-42dc-b910-2be07c1f9c17.png)

Sin embargo en el nivel del aire se cambia de ropa y añade al conjunto unas gafas y una máscara de gas. Dejo aquí los bocetos que he hecho:

![image](https://user-images.githubusercontent.com/90465415/147388936-950f5189-f6b9-4583-980e-579d5823d178.png)

Y este sería el turnaround de Shönu para el modelado:

![image](https://user-images.githubusercontent.com/90465415/147388958-fdab65d9-0aa4-440d-aed7-51b8c23a6924.png)

**Comment by alhgo** [comment]
Genial. Ya me diréis qué hacemos con los enemigos (no descartéis coger assets de Internet que tengan ya el modelado y las animaciones, aunque suponga usar diseños que no son los nuestros)

**Comment by LauFranky** [comment]
Lo tengo en cuenta, como acabo de decir en la respuesta del otro issue. Por cierto, entre hoy y mañana subiré ya todos los concepts y cerraré este issue.

**Comment by LauFranky** [comment]
**Concept de las criaturas enemigas**

![Criatura perro](https://user-images.githubusercontent.com/90465415/147786587-93edeb5c-207b-4034-afe5-d7a0d30847d7.jpg)

![Criaturas aves](https://user-images.githubusercontent.com/90465415/147786600-9329779c-c38e-4666-8ab8-28a61ed53e71.jpg)

**Comment by LauFranky** [comment]
Acerca del **diseño visual que tendrá el nivel del aire**, dejo aquí unas referencias muy buenas sobre lo que tengo en mente:

![image](https://user-images.githubusercontent.com/90465415/147786792-0c9ecc63-45b7-4b4c-8021-a083ec50fa7b.png)

![image](https://user-images.githubusercontent.com/90465415/147786784-37fc7fbc-c90a-4f9b-a6a8-deac50987bfa.png)

![image](https://user-images.githubusercontent.com/90465415/147786770-431f0a54-b666-4bc7-bba6-67dc9bb32dba.png)

![image](https://user-images.githubusercontent.com/90465415/147786744-854bce89-9003-4895-90a4-92cd1eebcf40.png)

![image](https://user-images.githubusercontent.com/90465415/147786712-da9aae34-e4ae-4c65-ac34-256b8e6251e4.png)

![image](https://user-images.githubusercontent.com/90465415/147786809-2e2476ab-0edd-49e8-8d71-98551cb213ff.png)

**Comment by LauFranky** [comment]
**Concept Boss del nivel**

![Boss](https://user-images.githubusercontent.com/90465415/147851664-c1da90a6-3b24-4b15-8d29-efed80c350ea.jpg)

**Comment by LauFranky** [comment]
**Concept enemigos humanos**

![Enemigos humanos](https://user-images.githubusercontent.com/90465415/147859393-7200f122-66d9-4c81-85ea-c20b089c39c2.jpg)
