### ISSUE TITLE
Texturizado

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#30]
- [x] Recopilación de texturas de materiales

**UVs y texturizado de personajes:**
- [x] Shönu
- [x] Dragón de aire
- [x] Boss
- [x] Enemigos humanos

**Texturizado escenario**
- [x] Props 
- [x] Obstáculos

**Preparación de imagenes e iluminación Skydome y escenario**
- [x] Skydome de día
- [x] Skydome anocheciendo
- [x] Zeppelines
- [x] Nubes
- [x] Islas flotantes

**Comment by yaigh** [comment]
Los materiales o los texturizados son lo último pero hay que tener las UV´S hechas de cada modelado y al final del juego meter todos los materiales directamente en Unity

**Comment by yaigh** [comment]
Vamos a empezar con las UV'S, vamos hacer las de Shönu para después meterlo en Mixamo y hacer las animaciones.
Antes de acabar el videojuego lo texturizaremos.
