### ISSUE TITLE
Animación

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#31]
**Shönu**
- [x] Caminar
- [x] Correr
- [x] Saltar
- [ ] Agacharse
- [x] Esquivar
- [x] Ataques básicos
- [x] Ataques con poder
- [x] Recibir daño
- [x] Caer
- [x] Muerte

**Enemigos humanos y boss**
- [x] Caminar
- [ ] Esquivar
- [x] Varios ataques
- [x] Recibir daño
- [x] Muerte

**Comment by alhgo** [comment]
Supongo que no nos hemos planteado hacer las animaciones, sino que las buscaremos hechas, ¿no? Lo digo por el tiempo:
[https://www.mixamo.com/#/?page=1&query=atack](https://www.mixamo.com/#/?page=1&query=atack)

Eso para los bípedos. Las criaturas lo veo más complicado

**Comment by yaigh** [comment]
Estoy haciendo pruebas con Shönu en la página de mixamo, los movimientos van muy bien, solo tenemos que corregir la malla de Shönu y vestirle pero creemos que vamos hacer todos los movimientos aquí.

https://user-images.githubusercontent.com/90465328/147874917-20c1413e-c61d-4371-9156-847aa723ecdc.mp4

**Comment by yaigh** [comment]
Sigo con las pruebas de Shönu en Mixamo, los movimientos funcionan muy bien , los brazos y las piernas responden bien a los movimientos, lo único malo es la ropa, más concretamente el pantalón porque hace pliegues raros en algunos movimientos, el resto de la ropa también funciona muy bien.

https://user-images.githubusercontent.com/90465328/148679171-e43a8347-aaea-428d-b248-5275153e9f82.mp4

https://user-images.githubusercontent.com/90465328/148679297-4b69135c-7e45-4792-b41e-cfb097b808f2.mp4

**Comment by yaigh** [comment]
Algunos videos son muy pesados para subirlos, por eso os los dejo aquí comprimidos por si los queréis ver.
Este video es de Shönu, muevo la cámara a su alrededor para que se puedan ver todos los movimientos.

[Mixamo - Google Chrome 2022-01-09 12-01-08.zip](https://github.com/CIFP-Jose-luis-Garci/Shakun/files/7834905/Mixamo.-.Google.Chrome.2022-01-09.12-01-08.zip)

**Comment by yaigh** [comment]
Algunos videos son muy pesados para subirlos, por eso os los dejo aquí comprimidos por si los queréis ver.
Este video es de Shönu, muevo la cámara a su alrededor para que se puedan ver todos los movimientos.

[Mixamo - Google Chrome 2022-01-09 12-01-08.zip](https://github.com/CIFP-Jose-luis-Garci/Shakun/files/7834905/Mixamo.-.Google.Chrome.2022-01-09.12-01-08.zip)

**Comment by yaigh** [comment]
**MOVIMIENTOS DE SHÖNU EN MIXAMO:**

- [ ] Low Crawl
- [ ] Big Jump
- [ ] Run
- [ ] Fast Run
- [ ] Run Look Back
- [ ] Running Up Stairs
- [ ] Running Slide?
- [ ] Death from right
- [ ] Walking
