### ISSUE TITLE
¿Hay tiempo para hacer criaturas no humanas?

### ISSUE THREAD

**Issue by alhgo** [CIFP-Jose-luis-Garci/Shakun#32]
Necesito saber qué criaturas se quieren hacer para la demos. Lo digo porque si no son bípedos y no encontramos assets disponibles para hacerlas, quizás haya que descartarlas en la demo por falta de tiempo

**Comment by LauFranky** [comment]
De criaturas tenía pensados una especie de perro y dos tipos de aves. ¿No se podrían conseguir los assets?

**Comment by alhgo** [comment]
Hola. Es antiguo este issue, pero ahora en navidad podemos efectivamente buscar assets que se ajusten a lo que buscamos. Tanto en la asset store de Unity, como modelos en Internet que estén ya riggeados y animados. Creo que eso es más fácil que hacerlos nosotros, aunque renunciemos a parte del diseño

**Comment by LauFranky** [comment]
Gracias Álvaro, voy a mirar lo de la asset store. De todas formas, como sé que no da tiempo a modelar todo ni por asomo, ya tengo varias páginas con modelados de todo tipo gratuitos. Pensaba tirar mucho de ellas sobre todo para el escenario y los props. Lo que había pensado también era descargar como tú dices, modelos para los enemigos y modificarlos un poco. Eso ahorra mucho tiempo e igualmente le puedo dar el aspecto que buscamos.
