### ISSUE TITLE
Introducción

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#4]
Concepto del juego: en dos o tres líneas.
Características principales: un listado de los pilares fundamentales que tendrá el juego
ya sea en el aspecto de jugabilidad, mecánicas, narrativa…

**Comment by yaigh** [comment]
Shak'un es un videojuego en el que el jugador controla a Shonü (el protagonista, un niño del tempo Shak'un), su misión es rescatar a los dragones, de este mundo fantástico, de la raza humana, ya que, los dragones son los portadores de los elementos que mantienen el mundo vivo.

El juego se caracteriza principalmente por su historia y por la idea que se transmite tras de ella, salvar a la tierra; por su estilo visual, como, el protagonista, el antagonista, los dragones, las criaturas enemigas y los escenarios; por ser un juego de plataforma en 3D; por la jugabilidad, los movimientos y los poderes que va a ir obteniendo nuestro jugador a lo largo del juego cada vez que rescate a un dragón y pase de nivel.
