### ISSUE TITLE
Género

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#5]
Género principal o combinación de géneros que tendrá el videojuego.

**Comment by MaikDitz** [comment]
![1366_2000](https://user-images.githubusercontent.com/90465468/141176335-b69927af-9a0b-469e-a344-d15dc0dfbfd1.jpeg)

Nuestro juego esta compuesto por mas de un género, como es la acción, la estrategia, y la aventura. Destacan estos tres porque al ser un mundo abierto y con mecánicas con combates variados ya estamos involucrando la acción. Luego no todo consta de pelearse sino que también hay que ser ingeniosos y buscar la forma de continuar con la historia.
Como subgéneros de nuestro juego es un hack´n slash, que consiste en que el jugador se enfrenta a enemigos mediante el uso de armas blancas, aunque también puede haber armas de fuego para derrotar a bastantes enemigos.
![maxresdefault](https://user-images.githubusercontent.com/90465468/141175266-5ac254a9-55bd-4132-9ad0-001a6a3e4ade.jpg)
