### ISSUE TITLE
Plataforma

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#6]
Consola, PC… Justificar por qué hemos elegido esa plataforma (podemos apoyarnos en los datos de AEVI).

**Comment by yaigh** [comment]
Shak'un va a ser un juego para consola (PlayStation y Xbox), controlado por mando. Hemos elegido esta plataforma porque según AEVI los usuarios utilizan más consolas que ordenadores para jugar.
Es un juego para un solo jugador.

**Comment by yaigh** [comment]
Shak'un esta pensado para un solo jugador. Va a ser un juego para consola (PlayStation o Xbox), controlado por un mando. Hemos elegido estas plataformas porque según AEVI hay un porcentaje mayor en los usuarios que juegan en consolas a los que juegan en el ordenador y también, porque nuestro equipo siempre ha preferido jugar en consolas y al tener mayor experiencia en esta plataforma nos resultará más fácil el desarrollo del juego.
