### ISSUE TITLE
Historia y narrativa

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#7]
-Lema
-Historia
-Plot Points
-Narrativa: indicar qué tipo de narrativa o narrativas se adaptan más a la historia y por qué, qué aporta al jugador, qué ventajas e inconvenientes tiene…

**Comment by LauFranky** [comment]
**Historia**
Hace mucho tiempo, los dragones eran el símbolo del equilibrio del mundo, hasta que un día, el líder de la raza humana Geylong decidió intentar obtener ese poder para sí mismo. Los dragones eran los sustentadores de los diferentes elementos y gracias a eso, el mundo tenía vida, pero ante la avaricia del líder uno a uno fueron siendo capturados.
Los dragones al ser retirados de sus respectivos templos, se van debilitando poco a poco y eso provoca que la tierra comience a morir.
Antes de que sucediera esto, los dragones siempre habían estado protegidos por una raza de humanos llamados Shak'un que vivían en un templo en las montañas. Estos existían con el único fin de proteger el equilibrio de la naturaleza, y para ello defendían y luchaban hasta la muerte por los dragones desde tiempos inmemoriales. Sin embargo, los humanos fueron aumentando en número y fuerza, y su sed de poder hizo que esta pequeña raza se quedara sin sus mejores guerreros. Ya no eran lo suficientemente fuertes para proteger a los dragones.
Entonces, ante un mundo que moría poco a poco, a unos humanos tremendamente poderosos y a la desolación e impotencia del templo Shak´un, Shönu, nuestro protagonista, decide emprender por su cuenta una misión de rescate, iniciando así su aventura por salvar a los dragones, a su raza y al mundo.
El niño emprende su propósito, e irá ciudad por ciudad enfrentándose a sus enemigos en diferentes ambientes infestados de criaturas deseosas de alimento. Tras superar cada uno de estos niveles, Shönu rescatará a cada dragón, los cuales le dotarán de un poder de entre los diferentes elementos, para ayudarle a llegar al líder Geylon y poder derrotarle.
Tras vencer a Geylhon y rescatar a todos los dragones, estos como gratitud y por prudencia a que pueda ocurrir algo similar en un futuro, le dejan quedarse a Shönu con el poder que le habían prestado, convirtiendose así en el máximo protector.

**Comment by LauFranky** [comment]
**Lema**
¡Conviértete en Protector!

**Comment by LauFranky** [comment]
**Narrativa**
Shak´un contará con una narrativa de espina. 
El videojuego comenzará contando la historia del pasado de los dragones y el mundo de forma lineal. Comentará paso por paso los sucesos que ocurrieron antes de lo que se encuentre el jugador al inicio de la aventura, sin embargo, a medida que se superen los niveles, habrán animáticas en las que se cuente el pasado de algún personaje o suceso en especial.

**Comment by yaigh** [comment]
**LEMA MEJORADO**
- ¡Tu misión, aniquilar a Geylhon!
- ¡Conviértete en el protector!
- **¡Únete al templo Shak'un y conviértete en el protector!** 
- ¡Tu misión, rescatar a los dragones!

**Comment by LauFranky** [comment]
**Plot points**
· Debido a unas sequía, la familia de Geylhon murió de hambre.
· Geylhon decide movilizar a los humanos para tomar los templos de los elementos y llevarse a los dragones.
· Mueren los mejores guerreros de Shak´un tras varias batallas con los humanos.
· Los humanos se hacen con los dragones.
· La Tierra empieza a morir. Las plantas mueren, el aire se va pudriendo y los animales se vuelven agresivos debido a la falta de alimento.
· El templo Shak´un está sumido en la desesperanza, pero Shönu decide escaparse a pesar de las advertencias en busca de los dragones.
· Le atacan criaturas y diferentes enemigos a lo largo del viaje.
· Los dragones están encerrados en una gran jaula y siendo torturados para que les cedan los poderes a los humanos.
· Cada dragón está custodiado por el jefe de cada ciudad (el enemigo más fuerte al que se tendrá que enfrentar Shönu para ir rescatándolos).
· Cada dragón que rescata, antes de huir libre le da una pequeña porte de su poder a Shönu para ayudarle en su misión.
· Cuando Shönu consigue llegar hasta Geylhon, ya es demasiado tarde. Geylhon ha matado al dragón de Luz y Oscuridad y ha obtenido su poder. Shönu peleará con los poderes que le dieron los otros dragones y Geylhon con el de Luz y Oscuridad.
· Cuando Shönu vence a Geylhon, recibe el poder de Luz y Oscuridad también.
· Los dragones se le aparecen en ese momento a Shönu y le ceden esa parte del poder que le dieron para convertirle en el protector de los dragones.

**Comment by LauFranky** [comment]
**LEMA**
¡Únete al templo Shak'un y conviértete en el protector!

**HISTORIA**
Hace mucho tiempo, los dragones eran el símbolo del equilibrio del mundo, hasta que un día, el líder de la raza humana Geylhon decidió intentar obtener ese poder para sí mismo. Los dragones eran los sustentadores de los diferentes elementos y gracias a eso, el mundo tenía vida, pero ante la avaricia del líder uno a uno fueron siendo capturados.
Los dragones al ser retirados de sus respectivos templos, se van debilitando poco a poco y eso provoca que la tierra comience a morir.
Antes de que sucediera esto, los dragones siempre habían estado protegidos por una raza de humanos llamados Shak'un que vivían en un templo en las montañas. Estos existían con el único fin de proteger el equilibrio de la naturaleza, y para ello defendían y luchaban hasta la muerte por los dragones desde tiempos inmemoriales. Sin embargo, los humanos fueron aumentando en número y fuerza, y su sed de poder hizo que esta pequeña raza se quedara sin sus mejores guerreros. Ya no eran lo suficientemente fuertes para proteger a los dragones.
Entonces, ante un mundo que moría poco a poco, a unos humanos tremendamente poderosos y a la desolación e impotencia del templo Shak´un, Shönu, nuestro protagonista, decide emprender por su cuenta una misión de rescate, iniciando así su aventura por salvar a los dragones, a su raza y al mundo.
El niño emprende su propósito, e irá ciudad por ciudad enfrentándose a sus enemigos en diferentes ambientes infestados de criaturas deseosas de alimento. Tras superar cada uno de estos niveles, Shönu rescatará a cada dragón, los cuales le dotarán de un poder de entre los diferentes elementos, para ayudarle a llegar al líder Geylhon y poder derrotarle.
Tras vencer a Geylhon y rescatar a todos los dragones, estos como gratitud y por prudencia a que pueda ocurrir algo similar en un futuro, le dejan quedarse a Shönu con el poder que le habían prestado, convirtiendose así en el máximo protector.

**PLOT POINTS**
- Debido a unas sequía, la familia de Geylhon murió de hambre.
- Geylhon decide movilizar a los humanos para tomar los templos de los elementos y llevarse a los dragones.
- Mueren los mejores guerreros de Shak´un tras varias batallas con los humanos.
- Los humanos se hacen con los dragones.
- La Tierra empieza a morir. Las plantas mueren, el aire se va pudriendo y los animales se vuelven agresivos debido a la falta de alimento.
- El templo Shak´un está sumido en la desesperanza, pero Shönu decide escaparse a pesar de las advertencias en busca de los dragones.
- Le atacan criaturas y diferentes enemigos a lo largo del viaje.
- Los dragones están encerrados en una gran jaula y siendo torturados para que les cedan los poderes a los humanos.
- Cada dragón está custodiado por el jefe de cada ciudad (el enemigo más fuerte al que se tendrá que enfrentar Shönu para ir rescatándolos).
- Cada dragón que rescata, antes de huir libre le da una pequeña porte de su poder a Shönu para ayudarle en su misión.
- Cuando Shönu consigue llegar hasta Geylhon, ya es demasiado tarde. Geylhon ha matado al dragón del Espacio-Tiempo y ha obtenido su poder. Shönu peleará con los poderes que le dieron los otros dragones y Geylhon con el de Espacio-Tiempo.
- Cuando Shönu vence a Geylhon, recibe el poder de Espacio-Tiempo también.
- Los dragones se le aparecen en ese momento a Shönu y le ceden esa parte del poder que le dieron para convertirle en el protector de los dragones.

**NARRATIVA**
Shak´un contará con una narrativa de espina.
El videojuego comenzará contando la historia del pasado de los dragones y el mundo de forma lineal. Comentará paso por paso los sucesos que ocurrieron antes de lo que se encuentre el jugador al inicio de la aventura, sin embargo, a medida que se superen los niveles, habrán animáticas en las que se cuente el pasado de algún personaje o suceso en especial.
