### ISSUE TITLE
Interfaz

### ISSUE THREAD

**Issue by LauFranky** [CIFP-Jose-luis-Garci/Shakun#9]
Mapa de navegación: diagrama de bloques donde se muestre la navegación del
usuario durante el juego
Menús
HUD

**Comment by MaikDitz** [comment]
La interfaz constara de varios menús dentro y fuera de juego. Primero tenemos el menú principal que es el que nos sale cuando entramos por primera vez al juego y es la ventana donde pone los apartados:
-Jugar
-Ajustes
-Salir del juego
![Menu_principal](https://user-images.githubusercontent.com/90465468/141169928-8c25d1a6-bb69-41f1-841c-b4de72490d03.png)

Luego, dentro de la sección jugar tenemos:
-Nuevo Juego
-Cargar partida (solo disponible si ya se ha jugado antes)
![menu_principal_2](https://user-images.githubusercontent.com/90465468/141171316-47a7fb21-d1fd-4bc6-8e59-0b78f9de8f0b.png)


En la sección de opciones tenemos unos ajustes muy generales de todos los juegos como puede ser:
-Volumen
-Idioma
-Calidad grafica
-Asignación de teclas
-Ajustes de la cámara
-Ajustes de pantalla
Cuando estemos dentro del juego tenemos dos cosas, un HUD y un menú de pausa del juego. En el HUD se puede apreciar el mapa (que estará siempre visible), las barras de vida y maná, las habilidades (para saber cuales estás usando en el momento) que, a parte de tenerlas visibles en pantalla para seleccionarlas tendrás una rueda de habilidades seleccionables.
![Interfaz](https://user-images.githubusercontent.com/90465468/141171012-cf00ce42-970d-4d87-810c-64758845fec4.png)

En el menú de pausa cuando estas dentro del juego aparecerán los apartados:
-Volver al juego
-Misiones
-Ajustes
-Guardar partida
-Guardar y salir
